config/routes.rb
Rails.application.routes.draw do
  get 'products/create'

  get 'products/edit'

  get 'devise/Seller'

  devise_for :sellers, controllers: { :sessions => "sellers/sessions",
                                      :registrations => "sellers/registrations" }
  devise_for :users, controllers: { :registrations => "users/registrations",
                                    :sessions => "users/sessions",
                                    :pages => "users/pages"}

  root "posts#index"


  # devise_scope :user do
  # 	root to: "devise/sessions#new"
  #   resources :posts
	# end

  resources :posts, shallow: true do
  	resources :comments
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :sellers do
    resources :products
  end

  resources :users do
    resources :images
    resources :friendships
  end

  resources :charges do
  end
  
  get '/:seller_id/:product_id/:advertiser_id/payment' => 'charges#new', as: 'buy_through_ad'


  get '/sign_in' => 'users/pages#sign_in', as: 'sign_in'
  get '/sign_up' => 'users/pages#sign_up', as: 'sign_up'

  get 'users/:id/show' => 'users/pages#show', as: 'user_profile'
  get 'sellers/:id/show' => 'sellers/pages#show', as: 'seller_profile'
  get 'users/:id/friendships/:friend_id/accept' => 'friendships#accept', as: 'user_friendship_accept'
  get 'users/:id/friendships/:friend_id/reject' => 'friendships#reject', as: 'user_friendship_reject'
  get 'users/:id/friendships/:friend_id/delete' => 'friendships#delete', as: 'user_friendship_delete'
  get 'products/get' => 'products#get'

  post 'adverts/create' => 'adverts#create', as: 'create_ad'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable

  has_many :posts
  has_many :comments
  has_many :images
  acts_as_voter

  has_many :friendships

  has_many :friends, -> { where "status = 'accepted'" }, :through => :friendships
  has_many :pending_friends, -> { where "status = 'pending'" }	, :through => :friendships, :source => :friend
  has_many :friend_requests, -> { where "status = 'requested'" }	, :through => :friendships, :source => :friend

  has_many :adverts

  def has_image?
  	!self.images.empty?
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/pages_controller.rb
class Users::PagesController < ApplicationController

  def show
    User.find(params[:id]) == current_user ? @user = current_user : @user = User.find(params[:id])
    @image = Image.new
    @friendship = Friendship.new
  end

  def sign_in
  	@user = User.new
  	@seller = Seller.new
  end

  private

  def page_params
  	params.require(:page).permit(:id)
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
  def create
  build_resource(sign_up_params)

  resource.save
  yield resource if block_given?
  if resource.persisted?
    if resource.active_for_authentication?
      set_flash_message! :notice, :signed_up
      sign_up(resource_name, resource)
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
      expire_data_after_sign_in!
      respond_with resource, location: after_inactive_sign_up_path_for(resource)
    end
  else
    clean_up_passwords resource
    set_minimum_password_length
    respond_with resource
  end
end

  # GET /resource/edit
  #def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def after_sign_up_path_for(resource)
     user_profile_path(resource)
   end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name ,:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password)
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    user_profile_path(resource)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/pages/show.html.erb
<div class="col-sm-4">
	<span class="pull-left">
 		<% if @user.has_image? %>
 			<%= image_tag(@user.images.first.file(:profile), class: "user-profile-image") %>
 		<% else %>
 			<%= image_tag("default_user_image.png", size: "200", class: "user-profile-image") %>
 		<% end %>
		<div class="profile_name">
			<h3><%= @user.full_name %></h3>

		<% if current_user == @user %>
			<p><%= link_to "Edit Profile", edit_user_registration_path%></p>
		<% end %>

 		<% if @user == current_user %>
 			<a href="" id="upload-image-link">Change your Profile Picture</a>
 			<div id="upload-image-form-container">
 				<%= form_for(@image, url: user_images_path(current_user), html: { multipart: true }) do |form| %>
 					<div class="field">
 						<%= form.label :file %> <i>(choose an image)</i><br />
 						<%= form.file_field :file %> <br />
 					</div>
 					<div class="actions">
 						<%= form.submit "Upload" %>
 					</div>
 					<% end %>
 			</div>
 		<% end %>
	</div>
	</span>
</div>

 <div class="col-sm-4">
	 <span class="pull-left">
	 	<% if current_user == @user %>
	 		<h1> Recent Activity: </h1>
	  		<% current_user.posts.reverse.each do |post| %>
	 	 			<div id="post_<%= post.id %>" class="text-center">
						<h2><%= link_to post.text, post_path(post) %></h2>
	 							<%= link_to post_path(post) do %>
	 								<% if post.image.exists? %>
	 									<p><%= image_tag post.image.url(:medium) %></p>
	 								<% end %>
	 							<% end %>
							<a href="/users/<%= post.user.id %>/show"><%= post.user.first_name %> <%= post.user.last_name %></a><br>
	 						<span><%= post.created_at.strftime("%d %b %Y %H:%M") %></span>
	 					</div>
	 				<% end %>
	 	<% else %>
	 				Posts submitted by the user: </h1>
	 		 			<% @user.posts.reverse.each do |post| %>
	 			 			<div id="post_<%= post.id %>" class="text-center">
								<h2><%= link_to post.text, post_path(post) %></h2>
	 						 		<%= link_to post_path(post) do %>
	 							 <% if post.image.exists? %>
	 								 <p><%= image_tag post.image.url(:medium) %></p>
	 							 <% end %>
	 						 <% end %>
							 <a href="/users/<%= post.user.id %>/show"><%= post.user.first_name %> <%= post.user.last_name %></a><br>
	 					 	 <span><%= post.created_at.strftime("%d %b %Y %H:%M") %></span>
	 				 		 </div>
	 		 		 <% end %>
	 		<% end %>
	</span>
</div>


 <div class="col-sm-4">

	  <% if current_user %>
	  	<div class="row">

				<div class="signed-in-header col-lg-12 text-center">
					<ul class="nav navbar-nav">
						<li class="add-friend">
							<%= form_tag(user_friendships_path(current_user), :class => "add-friend-form") do %>
								<div class="field">
									<%= label_tag  :friend_email, "Add Friend" %></i><br />
									<%= email_field_tag :friend_email, nil, :placeholder => "Enter friends email", :required => true  %> <br />
								</div>
								<div class="actions">
									<%= submit_tag "Send Friend Request" %>
								</div>
							<% end %>
						</li>
					</ul>
				</div>
	  	</div>
	  <% end %>

	  <hr class="divider">

		<div class="row">
				<h5 class="text-center"><%= @user.full_name %>'s friends</h5>
			  <% @user.friends.each do |friend| %>
				  <% time = Time.new %>
				  <div class="user-friend-container col-xs-6 col-md-3 text-center">
					  <% if friend.has_image? %>
						  <%= image_tag(friend.images.first.file(:thumbnail), class: "user-profile-image col-md-12") %>
					  <% else %>
						  <%= image_tag("default_user_image.png", size: "50", class: "user-profile-image col-md-12") %>
					  <% end %>
					  <span><%= link_to "#{friend.full_name}", user_profile_path(friend) %></span>
					  <% if friend.last_seen > (time - 300) %>
						  <span class="online-symbol"></span>
					  <% else %>
						  <span class="offline-symbol"></span>
					  <% end %>
					  <%= link_to "Remove Friend", user_friendship_delete_path(current_user,friend) if @user == current_user %>
		  		</div>
				<% end %>
	  </div>

		<hr class="divider">

		<div class="row">
			<h5 class="text-center"><%= @user.full_name %>'s recommended products</h5>
			<% @user.adverts.first(10).shuffle.each do |advert| %>
				<div class="user-ad-container col-md-3">
					<%= image_tag advert.post.image %>
					<p class="text-center"><%= advert.product.product_name %></p>
				</div>
			<% end %>
		</div>
	</div>

<script>
	$( function() {
		$(' #upload-image-form-container').hide();
	});

	$('#upload-image-link').click(function(event) {
		event.preventDefault();
		$('#upload-image-form-container').toggle();
	});

	$('#file-field').change(function() {
		$('#upload-image-button').prop('disabled', false);
	});
</script>

app/views/users/pages/sign_in.html.erb
<body class ="signin-bg">
<div class="flip-container">
	<div id="side-1" class="flip">
		<div id="user-form">
		  <h2>Log in as User</h2>
			<%= form_for @user, as: :user, :url => session_path(:user) do |f| %>
			  <div class="field">
			    <%= f.label :email %><br />
			    <%= f.email_field :email, autofocus: true %>
			  </div>
			  <div class="field">
			    <%= f.label :password %><br />
			    <%= f.password_field :password, autocomplete: "off" %>
			  </div>
		    <div class="field">
		      <%= f.check_box :remember_me %>
		      <%= f.label :remember_me %>
		    </div>
			  <div class="actions">
			    <%= f.submit "Log in", :id => "user-log-in-button" %>
			  </div>
			<% end %>
			<a id="signup" href="#">OR sign in as a SELLER??</a>
		</div>
	</div>
	<div id="side-2" class="flip">
		<div id="seller-form">
			<h2>Log in as Seller</h2>
		  <%= form_for @seller, as: :seller, :url => session_path(:seller) do |f| %>
			  <div class="field">
			    <%= f.label :email %><br />
			    <%= f.email_field :email, autofocus: true %>
			  </div>
			  <div class="field">
			    <%= f.label :password %><br />
			    <%= f.password_field :password, autocomplete: "off" %>
			  </div>
		    <div class="field">
		      <%= f.check_box :remember_me %>
		      <%= f.label :remember_me %>
		    </div>
			  <div class="actions">
			    <%= f.submit "Log in", :id => "seller-log-in-button" %>
			  </div>
			<% end %>
			<a id="create" href="#">OR sign up as a USER??</a>
		</div>
	</div>
</div>


<script>
document.getElementById( 'signup' ).addEventListener( 'click', function( event ) {

    event.preventDefault();
    document.getElementById( 'side-2' ).className = 'flip flip-side-1';
    document.getElementById( 'side-1' ).className = 'flip flip-side-2';

}, false );

document.getElementById( 'create' ).addEventListener( 'click', function( event ) {

    event.preventDefault();
    document.getElementById( 'side-2' ).className = 'flip';
    document.getElementById( 'side-1' ).className = 'flip';

}, false );

</script>

app/views/users/pages/sign_up.html.erb
<body class="signup-bg">
	
<div class="flip-container">
	<div id="side-1" class="flip">
		<div id="user-form">
			<h2>Sign up as User</h2>
			<%= form_for User.new, as: :user, :url => registration_path(:user) do |f| %>
			<div class="field">
	    	<%= f.label :first_name %><br />
	    	<%= f.text_field :first_name, autofocus: true %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :last_name %><br />
	    	<%= f.text_field :last_name %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :username %><br />
	    	<%= f.text_field :username %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :email %><br />
	    	<%= f.email_field :email %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :password %>
	    	<% if @minimum_password_length %>
	    	<em>(<%= @minimum_password_length %> characters minimum)</em>
	    	<% end %><br />
	    	<%= f.password_field :password, autocomplete: "off" %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :password_confirmation %><br />
	    	<%= f.password_field :password_confirmation, autocomplete: "off" %>
	  	</div>
	  	<div class="actions">
	    	<%= f.submit "Sign up" %>
	  	</div>
			<% end %>
			<p><a id="signup" href="#">OR sign up as a SELLER??</a><p>
		</div>
	</div>
	<div id="side-2" class="flip">
		<div id="seller-form">
			<h2>Sign up as Seller</h2>
			<%= form_for Seller.new, as: :seller, :url => registration_path(:seller) do |f| %>
			<div class="field">
				<%= f.label :shop_name %><br />
				<%= f.text_field :shop_name, autofocus: true %>
			</div>
			<div class="field">
				<%= f.label :first_name %><br />
				<%= f.text_field :first_name, autofocus: true %>
			</div>
			<div class="field">
				<%= f.label :last_name %><br />
				<%= f.text_field :last_name %>
			</div>
			<div class="field">
				<%= f.label :email %><br />
				<%= f.email_field :email %>
			</div>
			<div class="field">
				<%= f.label :password %>
				<% if @minimum_password_length %>
				<em>(<%= @minimum_password_length %> characters minimum)</em>
				<% end %><br />
				<%= f.password_field :password, autocomplete: "off" %>
			</div>
			<div class="field">
				<%= f.label :password_confirmation %><br />
				<%= f.password_field :password_confirmation, autocomplete: "off" %>
			</div>
			<div class="actions">
				<%= f.submit "Sign up" %>
			</div>
			<% end %>
			<a id="create" href="#">OR sign up as a USER??</a>
		</div>
	</div>
</div>

<script>
document.getElementById( 'signup' ).addEventListener( 'click', function( event ) {

    event.preventDefault();
    document.getElementById( 'side-2' ).className = 'flip flip-side-1';
    document.getElementById( 'side-1' ).className = 'flip flip-side-2';

}, false );

document.getElementById( 'create' ).addEventListener( 'click', function( event ) {

    event.preventDefault();
    document.getElementById( 'side-2' ).className = 'flip';
    document.getElementById( 'side-1' ).className = 'flip';

}, false );

</script>