config/routes.rb
Rails.application.routes.draw do
  get 'products/create'

  get 'products/edit'

  get 'devise/Seller'

  devise_for :sellers, controllers: { :sessions => "sellers/sessions",
                                      :registrations => "sellers/registrations" }
  devise_for :users, controllers: { :registrations => "users/registrations",
                                    :sessions => "users/sessions",
                                    :pages => "users/pages"}

  root "posts#index"


  # devise_scope :user do
  # 	root to: "devise/sessions#new"
  #   resources :posts
	# end

  resources :posts, shallow: true do
  	resources :comments
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :sellers do
    resources :products
  end

  resources :users do
    resources :images
    resources :friendships
  end

  resources :charges do
  end
  
  get '/:seller_id/:product_id/:advertiser_id/payment' => 'charges#new', as: 'buy_through_ad'


  get '/sign_in' => 'users/pages#sign_in', as: 'sign_in'
  get '/sign_up' => 'users/pages#sign_up', as: 'sign_up'

  get 'users/:id/show' => 'users/pages#show', as: 'user_profile'
  get 'sellers/:id/show' => 'sellers/pages#show', as: 'seller_profile'
  get 'users/:id/friendships/:friend_id/accept' => 'friendships#accept', as: 'user_friendship_accept'
  get 'users/:id/friendships/:friend_id/reject' => 'friendships#reject', as: 'user_friendship_reject'
  get 'users/:id/friendships/:friend_id/delete' => 'friendships#delete', as: 'user_friendship_delete'
  get 'products/get' => 'products#get'

  post 'adverts/create' => 'adverts#create', as: 'create_ad'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { large: '500x500>', medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :adverts

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :require_permisson, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      flash[:notice] = 'Post did not save'
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post deleted'
    redirect_to posts_path
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    respond_to do |format|
      format.html { redirect_back(fallback_location: posts_path(@post)) }
      format.json { render json: { count: @post.liked_count } }
      format.js   { render :layout => false }
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    respond_to do |format|
      format.html { redirect_back(fallback_location: posts_path(@post)) }
      format.json { render json: { count: @post.disliked_count } }
      format.js   { render :layout => false }
    end
  end

  private

  def require_permisson
    post = Post.find(params[:id])
    if current_user != post.user
      flash[:notice] = 'You are not the owner of this post'
      redirect_back
    end
  end

  def post_params
    params.require(:post).permit(:text, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/downvote.js.erb
$('span.dislike-<%= @post.id %>').bind('ajax:success', function() {

   $('.up-<%= @post.id %>').text(<%= @post.get_upvotes.size %>);
   $('span.dislike-<%= @post.id %>').replaceWith(
     '<span class="like-<%= @post.id %>"><%= link_to "Like", like_post_path(@post), method: :put, remote: true, class: 'like'  %></span>'
    );
});

app/views/posts/edit.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<span class="intro_message">
  <p>News to share? Friends to update? Items to sell? Then go ahead and <%= link_to "Create a post.", new_post_path %></p>
</span>
<% if @posts.any? %>
  <% @posts.reverse.each do |post| %>
    <div id="post_<%= post.id %>">
      <div class ="newsfeed">
        <div class="well">
        <% if post.user.has_image? %>
          <div class="profile_pic"><%= image_tag post.user.images.first.file(:profile), class: "img-thumbnail", alt: "Cinque Terre", width: "50", height: "50" %></div>
        <% else %>
          <div class ="profile_pic"><%= image_tag "default_user_image.png",class: "img-thumbnail", alt: "Cinque Terre", width: "50", height: "50" %></div>
        <% end %>
          <div class="name_and_time">
            <a href="/users/<%= post.user.id %>/show"><%= post.user.first_name %> <%= post.user.last_name %></a><br>
            <span><%= post.created_at.strftime("%d %b %Y %H:%M") %></span>
          </div><br />
          <% unless post.image.exists? %>
            <h4> <%= post.text %> </h4>
          <% else %>
            <h4> <%= link_to post.text, post_path(post) %> </h4>
            <%= link_to post_path(post) do %>
            <p><%= image_tag post.image.url(:medium) %></p>
            <% end %>
          <% end %>
          <% if @user %>
            <% if current_user.voted_up_on?(post) %>
              <span class="dislike-<%= post.id %>">
                <%= link_to "Unlike", dislike_post_path(post), method: :put, remote: true, class: 'dislike' %>
              </span>
            <% else %>
              <span class="like-<%= post.id %>">
                <%= link_to "Like", like_post_path(post), method: :put, remote: true, class: 'like'  %>
              </span>
            <% end %>
          | <span class="glyphicon glyphicon-thumbs-up"></span>
          <span class="up-<%= post.id %>"><%= post.get_upvotes.size %></span>
        <hr class ="divider">
        <% end %>

        <% if current_user == post.user %>
          <div class="edit_and_delete_posts">
            <div class="dropdown div-inline">
              <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown">
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Post", edit_post_url(post) %></li>
                <li><%= link_to "Delete Post", post_path(post), method: :delete %></li>
              </ul>
            </div>
          </div>
        <% end %>

        <div class='comments_div'>
           <%= render post.comments %>
        </div>

          <% if current_user %>
            <%= form_for [post, post.comments.new ], remote: true do |f| %>
              <%= f.text_area :text, placeholder: 'Add a comment' %>
              <%= f.submit 'Comment' %>
              <% end %>
          <% else%>
            <p>You need to <%= link_to "sign in", new_user_session_path %> to comment</p>
          <% end %>
        </div>
      </div>
  <% end %>
<% end %>

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div id="post_<%= @post.id %>" class="text-center">
  <div class ="newsfeed">
    <div class="well">
      <% if @post.image_file_name.nil? %>
        <h2><%= @post.text %></h2>
      <% else %>
        <h2><%= @post.text %></h2>
          <div id="canvas-wrap">
            <% if @post.user == current_user %>
              <canvas id="canvas"   style="background-image: url('<%= @post.image.url%>');"></canvas>
              <div id="overlay"></div>
            <% else %>
              <div id="post-image" style="background-image: url('<%= @post.image.url%>');">
                <% if @post.adverts.any? %>
                  <% @post.adverts.each do |advert| %>
                    <div class="user-ad" style="width:<%= advert.width %>; height:<%= advert.height %>; top:<%= advert.top %>; left:<%= advert.left %>;" data-productname="<%= advert.product.product_name %>"><a href="<%= buy_through_ad_path(advert.product.seller,advert.product,@post.user) %>" class="buy-product-through-ad-link"></a></div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
       <% end %>



        <% if @user %>
          <% if current_user.voted_up_on?(@post) %>
            <span class="dislike-<%= @post.id %>">
              <%= link_to "Unlike", dislike_post_path(@post), method: :put, remote: true, class: 'dislike' %>
            </span>
          <% else %>
            <span class="like-<%= @post.id %>">
              <%= link_to "Like", like_post_path(@post), method: :put, remote: true, class: 'like'  %>
            </span>
          <% end %>
        <% end %>


          <span class="glyphicon glyphicon-thumbs-up"></span>
          <span class="up-<%= @post.id %>"><%= @post.get_upvotes.size %></span>

        <hr class ="divider">
        <% if @post.user == current_user %>
          <div class="edit_and_delete_posts">
            <div class="dropdown div-inline">
              <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown">
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Post", edit_post_url(@post) %></li>
                <li><%= link_to "Delete Post", post_path(@post), method: :delete %></li>
              </ul>
            </div>
          </div>
        <% end %>
          <div class='comments_div'>
            <%= render @post.comments %>
          </div>
          <% if current_user %>
            <%= form_for [@post, @post.comments.new ], remote: true do |f| %>
              <%= f.text_area :text, placeholder: 'Add a comment' %>
              <%= f.submit 'Comment' %>
            <% end %>
          <% else%>
            <p>You need to <%= link_to "sign in", new_user_session_path %> to comment</p>
          <% end %>
        <% if @post.user == current_user %>
          <input id="adverts-checkbox" type="checkbox" name="adverts" value="adverts">Add advert
          <form id="create-ads-form" action="/adverts/create" method="post">
            <input id="product_id" type="hidden" name="product_id" value="0" >
            <input id="post_id" type="hidden" name="post_id" value="<%= params[:id] %>" >
            <input id="user_id" type="hidden" name="user_id" value="<%= current_user.id %>" >
            <input id="create-ad-button" type="submit" value="Create Ad" disabled>
          </form>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--Hover script-->
<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>

<% if current_user == @post.user %>
  <script>


    initDraw(document.getElementById('canvas'));

    function initDraw(canvas) {

      function setMousePosition(e) {
        var ev = e || window.event;
        if (ev.pageX) { //Moz
          mouse.x = ev.pageX -  $('#canvas-wrap').offset().left;
          mouse.y = ev.pageY -  $('#canvas-wrap').offset().top;
        } else if (ev.clientX) { //IE
          mouse.x = ev.clientX -  $('#canvas-wrap').offset().left;
          mouse.y = ev.clientY -  $('#canvas-wrap').offset().top;
        }
      }

      var mouse = {
        x: 0,
        y: 0,
        startX: 0,
        startY: 0
      };
      var element = null;

      canvas.onmousemove = function(e) {
        setMousePosition(e);
        if (element !== null) {
          element.style.width = Math.abs(mouse.x - mouse.startX) + 'px';
          element.style.height = Math.abs(mouse.y - mouse.startY) + 'px';
          element.style.left = (mouse.x - mouse.startX) < 0 ? mouse.x + 'px' : mouse.startX + 'px';
          element.style.top = (mouse.y - mouse.startY) < 0 ? mouse.y = 'px' : mouse.startY + 'px';
        }
      }

      var overlay = document.getElementById('overlay');

      canvas.onclick = function(e) {
        if (element !== null) {
          $('.new-ad').on('click', function(event) {
            this.remove();
            $('#create-ad-button').prop('disabled',true);
          });
          convertStylesToPercentages();
          element.style.border = "1px solid #fff";
          element = null;
          displayProductSearch();
          canvas.style.cursor = "default";
        } else if ($('.new-ad').length < 1 && document.getElementById('adverts-checkbox').checked == true) {
          $('#create-ad-button').prop('disabled',false);
          mouse.startX = mouse.x;
          mouse.startY = mouse.y;
          element = document.createElement('div');
          element.className = 'new-ad';
          element.style.left = mouse.x + 'px';
          element.style.top = mouse.y + 'px';
          element.style.border = "1px dashed #fff"
          canvas.style.cursor = "crosshair";
          overlay.appendChild(element);
        }
      }

      var changeTimer = false;

      function displayProductSearch() {
        input = document.createElement('input');
        input.id = 'product-search-input';
        input.placeholder = 'Search for product';
        //set search inputs onclick event here
        input.onclick =function(event) {
            event.stopPropagation();
        };
        // set search inputs onchange here
        input.onchange = function() {
          $.ajax({
            url: '/products/get',
            type: 'get',
            data: {
              search_string : input.value,
            },
            dataType: 'json',
            success : function(data) {
              appendSuggestedProducts(data);
              console.log(data)
            }
          })
        };
        $('.new-ad').append(input)
      }

      function appendSuggestedProducts(data) {
        container = document.createElement('div');
         for (i=0; i<data.products.length; i++) {
          product = data.products[i]
          container.id = "suggested-products";
          image = $('<img>');
          heading = $('<h5></h5>').text(product.product_name);
          description = $('<p><p>').text(product.product_description);
          price = $('<p></p>').text('£'+product.price);
          addItem = $('<a class="addItem">Add this Item</a>');
          addItem.click(function(event) {
            event.stopPropagation();
            event.preventDefault();
            $('#product_id').prop('value',product.id);
            $('#suggested-products, #product-search-input').remove();
          });
          suggestedProductContainer = $('<div></div>').prop('class',"suggested-product-container")
          $(suggestedProductContainer).append(image,heading,description,price,addItem);
          $(container).append(suggestedProductContainer);
         }

        $('.new-ad').append(container);

      }

      function convertStylesToPercentages() {
        element.style.width = ( ( $(element).outerWidth() / $('#overlay').width() ) * 100 ) + "%";
        element.style.height = ( ( $('.new-ad').height() / $('#canvas').height() ) * 100 ) + "%";
        element.style.left = ( ( $(element).position().left / $('#overlay').width() ) * 100 ) + "%";
        element.style.top = ( ( $(element).position().top / $('#canvas').height() ) * 100 ) + "%";
      }
    }

    $('#create-ad-button').click(function(event) {
      var newAd = $('.new-ad')[0];


      event.preventDefault();
      $.ajax({
        url: '/adverts/create',
        type: 'post',
        data: {
               width: newAd.style.width,
               height: newAd.style.height,
               left: newAd.style.left,
               top: newAd.style.top,
               product_id: $('#product_id').prop('value'),
               post_id : $('#post_id').prop('value'),
               user_id : $('#user_id').prop('value'),
              },
        dataType: 'json',
        success: function(data) {
          console.log(data+ "was sent")
          $('.new-ad').remove();
          $('#create-ad-button').prop('disabled',true);
        }
      });
    });



  </script>
<% end %>

<script type="text/javascript">
  $('.user-ad').on('mouseenter', function(event) {
      p = $('<p class="product-name"></p>')
      p.text(this.attributes['data-productname'].textContent);
      console.log(this,p);
      $(this).append(p);
    });

  $('.user-ad').on('mouseleave', function(event) {
      p = $('.user-ad p');
      p.remove();
    });

</script>

app/views/posts/upvote.js.erb
$('span.like-<%= @post.id %>').bind('ajax:success', function() {

   $('.up-<%= @post.id %>').text(<%= @post.get_upvotes.size %>);
   $('span.like-<%= @post.id %>').replaceWith(
     '<span class="dislike-<%= @post.id %>"><%= link_to "Unlike", dislike_post_path(@post), method: :put, remote: true, class: 'dislike' %></span>'
    );
});