config/routes.rb
Rails.application.routes.draw do
  get 'products/create'

  get 'products/edit'

  get 'devise/Seller'

  devise_for :sellers, controllers: { :sessions => "sellers/sessions",
                                      :registrations => "sellers/registrations" }
  devise_for :users, controllers: { :registrations => "users/registrations",
                                    :sessions => "users/sessions",
                                    :pages => "users/pages"}

  root "posts#index"


  # devise_scope :user do
  # 	root to: "devise/sessions#new"
  #   resources :posts
	# end

  resources :posts, shallow: true do
  	resources :comments
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :sellers do
    resources :products
  end

  resources :users do
    resources :images
    resources :friendships
  end

  resources :charges do
  end
  
  get '/:seller_id/:product_id/:advertiser_id/payment' => 'charges#new', as: 'buy_through_ad'


  get '/sign_in' => 'users/pages#sign_in', as: 'sign_in'
  get '/sign_up' => 'users/pages#sign_up', as: 'sign_up'

  get 'users/:id/show' => 'users/pages#show', as: 'user_profile'
  get 'sellers/:id/show' => 'sellers/pages#show', as: 'seller_profile'
  get 'users/:id/friendships/:friend_id/accept' => 'friendships#accept', as: 'user_friendship_accept'
  get 'users/:id/friendships/:friend_id/reject' => 'friendships#reject', as: 'user_friendship_reject'
  get 'users/:id/friendships/:friend_id/delete' => 'friendships#delete', as: 'user_friendship_delete'
  get 'products/get' => 'products#get'

  post 'adverts/create' => 'adverts#create', as: 'create_ad'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advert.rb
class Advert < ApplicationRecord
	belongs_to :post
	belongs_to :user
	belongs_to :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord

	belongs_to :user
	belongs_to :friend, :class_name => "User"

	def self.request(user,friend)
		unless user == friend or Friendship.exists?(user: user, friend: friend)
			transaction do
				create(:user => user, :friend => friend, :status => 'pending')
				create(:user => friend, :friend => user, :status => 'requested')
			end
		end
	end

	def self.accept(user,friend)
		transaction do
			accepted_at = Time.now
			accept_one_side(user,friend,accepted_at)
			accept_one_side(friend,user,accepted_at)
		end
	end

	def self.accept_one_side(user,friend,accepted_at)
		request = find_by_user_id_and_friend_id(user,friend)
		request.update(:status => 'accepted', :accepted_at => accepted_at)
	end

	def self.reject(user,friend)
		transaction do
			reject_one_side(user,friend)
			reject_one_side(friend,user)
		end
	end

	def self.reject_one_side(user,friend)
		request = find_by_user_id_and_friend_id(user,friend)
		request.update(:status => 'rejected')
	end

	def self.remove(user,friend)
		transaction do
			remove_one_side(user,friend)
			remove_one_side(friend,user)
		end
	end

	def self.remove_one_side(user,friend)
		request = find_by_user_id_and_friend_id(user,friend)
		request.delete
	end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_attached_file :file, :styles => {:thumbnail => "50x50", :profile => "200x200"}
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/
end

app/models/payment.rb
class Payment < ApplicationRecord
  def process_payment
    customer = Stripe::Customer.create email: email,
                                       card: card_token

    Stripe::Charge.create customer: customer.id,
                          amount: product.price * 100,
                          description: product.name,
                          currency: 'gbp'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { large: '500x500>', medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :adverts

end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :seller

	has_attached_file :image, styles: { large: '500x500>', medium: '300x300>', thumb: '100x100>' }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	has_many :adverts

	def has_image?
		image_file_name != nil
	end
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable

  has_many :posts
  has_many :comments
  has_many :images
  acts_as_voter

  has_many :friendships

  has_many :friends, -> { where "status = 'accepted'" }, :through => :friendships
  has_many :pending_friends, -> { where "status = 'pending'" }	, :through => :friendships, :source => :friend
  has_many :friend_requests, -> { where "status = 'requested'" }	, :through => :friendships, :source => :friend

  has_many :adverts

  def has_image?
  	!self.images.empty?
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :require_permisson, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      flash[:notice] = 'Post did not save'
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post deleted'
    redirect_to posts_path
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    respond_to do |format|
      format.html { redirect_back(fallback_location: posts_path(@post)) }
      format.json { render json: { count: @post.liked_count } }
      format.js   { render :layout => false }
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    respond_to do |format|
      format.html { redirect_back(fallback_location: posts_path(@post)) }
      format.json { render json: { count: @post.disliked_count } }
      format.js   { render :layout => false }
    end
  end

  private

  def require_permisson
    post = Post.find(params[:id])
    if current_user != post.user
      flash[:notice] = 'You are not the owner of this post'
      redirect_back
    end
  end

  def post_params
    params.require(:post).permit(:text, :image)
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrowdMarket</title>
    <%= csrf_meta_tags %>
    <link href = "//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel = "stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="top" class="navbar navbar-fixed-top navbar-inverse">
     <div class="container">
        <%= link_to "CrowdMarket", '/', id: "logo", class: "pull-left" %> 
        <nav>
         <ul class="nav navbar-nav navbar-right pull-right">
          <li><%= link_to "Home", '/'   %></li>
          <% if current_user || current_seller %>
            <% if current_user %>
              <li><%= link_to "Profile", user_profile_path(current_user) %></li>
            <% elsif current_seller %>
              <li><%= link_to "Profile", seller_profile_path(current_seller) %></li>
            <% end %>
         		<% if current_user %>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <li>
                <a id="friend-requests-link" href = "#">Friend Requests <% if @user.friend_requests.count > 0 %><span class = "badge"><%= @user.friend_requests.count %></span><% end %></a>
                <div id="friend-requests-container">
                  <% @user.friend_requests.each do |user| %>
                    <div class="friend-request-details">
                      <% if user.has_image? %>
                        <%= image_tag(user.images.first.file(:thumbnail)) %>
                      <% else %>
                        <%= image_tag("default_user_image.png", size: "50") %>
                      <% end %>
                      <span class="user-full-name"><%= user.full_name %></span>
                      <%= link_to "Accept Request", user_friendship_accept_path(current_user,user), class: "friend-request-button" %>
                      <%= link_to "Reject Request", user_friendship_reject_path(current_user,user), class: "friend-request-button" %>
                    </div>
                  <% end %>
                </div>
              </li>
            <% elsif current_seller %>
              <li><%= link_to "Sign out", destroy_session_path(current_seller), method: :delete %></li>
            <% end %>
          <% else %>
            <li><%= link_to "Sign in", sign_in_path %></li>
            <li><%= link_to "Sign up", sign_up_path %></li>
         	<% end %>
         </ul>
       </nav>
     </div>
    </header>
    <div class="container">
      <%= notice %>
      <%= yield %>
    </div>
    <script>
      $( function() {
        $('#friend-requests-container').hide();
      });

      $('#friend-requests-link').click(function(event) {
        event.preventDefault();
        $('#friend-requests-container').toggle();
      });
    </script>
  </body>
</html>